/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CinemasRouteImport } from './routes/cinemas'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as ApiPublicHooksScrapeCinemasRouteImport } from './routes/api/public/hooks/scrape-cinemas'
import { Route as ApiPublicHooksScrapeEventsRouteImport } from './routes/api/public/hooks/scrape-events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemasRoute = CinemasRouteImport.update({
  id: '/cinemas',
  path: '/cinemas',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScrapeCinemasRoute =
  ApiPublicHooksScrapeCinemasRouteImport.update({
    id: '/api/public/hooks/scrape-cinemas',
    path: '/api/public/hooks/scrape-cinemas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScrapeEventsRoute =
  ApiPublicHooksScrapeEventsRouteImport.update({
    id: '/api/public/hooks/scrape-events',
    path: '/api/public/hooks/scrape-events',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cinemas': typeof CinemasRoute
  '/events': typeof EventsRoute
  '/movies': typeof MoviesRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/public/hooks/scrape-cinemas': typeof ApiPublicHooksScrapeCinemasRoute
  '/api/public/hooks/scrape-events': typeof ApiPublicHooksScrapeEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cinemas': typeof CinemasRoute
  '/events': typeof EventsRoute
  '/movies': typeof MoviesRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/public/hooks/scrape-cinemas': typeof ApiPublicHooksScrapeCinemasRoute
  '/api/public/hooks/scrape-events': typeof ApiPublicHooksScrapeEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cinemas': typeof CinemasRoute
  '/events': typeof EventsRoute
  '/movies': typeof MoviesRoute
  '/listing/$id': typeof ListingIdRoute
  '/api/public/hooks/scrape-cinemas': typeof ApiPublicHooksScrapeCinemasRoute
  '/api/public/hooks/scrape-events': typeof ApiPublicHooksScrapeEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cinemas'
    | '/events'
    | '/movies'
    | '/listing/$id'
    | '/api/public/hooks/scrape-cinemas'
    | '/api/public/hooks/scrape-events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cinemas'
    | '/events'
    | '/movies'
    | '/listing/$id'
    | '/api/public/hooks/scrape-cinemas'
    | '/api/public/hooks/scrape-events'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cinemas'
    | '/events'
    | '/movies'
    | '/listing/$id'
    | '/api/public/hooks/scrape-cinemas'
    | '/api/public/hooks/scrape-events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CinemasRoute: typeof CinemasRoute
  EventsRoute: typeof EventsRoute
  MoviesRoute: typeof MoviesRoute
  ListingIdRoute: typeof ListingIdRoute
  ApiPublicHooksScrapeCinemasRoute: typeof ApiPublicHooksScrapeCinemasRoute
  ApiPublicHooksScrapeEventsRoute: typeof ApiPublicHooksScrapeEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinemas': {
      id: '/cinemas'
      path: '/cinemas'
      fullPath: '/cinemas'
      preLoaderRoute: typeof CinemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-cinemas': {
      id: '/api/public/hooks/scrape-cinemas'
      path: '/api/public/hooks/scrape-cinemas'
      fullPath: '/api/public/hooks/scrape-cinemas'
      preLoaderRoute: typeof ApiPublicHooksScrapeCinemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scrape-events': {
      id: '/api/public/hooks/scrape-events'
      path: '/api/public/hooks/scrape-events'
      fullPath: '/api/public/hooks/scrape-events'
      preLoaderRoute: typeof ApiPublicHooksScrapeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CinemasRoute: CinemasRoute,
  EventsRoute: EventsRoute,
  MoviesRoute: MoviesRoute,
  ListingIdRoute: ListingIdRoute,
  ApiPublicHooksScrapeCinemasRoute: ApiPublicHooksScrapeCinemasRoute,
  ApiPublicHooksScrapeEventsRoute: ApiPublicHooksScrapeEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
